services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: go-project-mssql
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - go-network

  mongodb:
    image: mongo:7.0
    container_name: go-project-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - go-network

volumes:
  mssql_data:
  mongo_data:

networks:
  go-network:
    driver: bridge
